### ISSUE TITLE
QRReader impossible to run

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#18]
I am trying to run the QRReader I have install zxing4p3 however I still have this error:

The class "ZXING4P" doesn't exist.

I have install it from the import library in processign and the libraries has been successfully installed in libraries.

Si nthere anything else to do?

**Comment by vaap1997** [comment]
Hello Arnaud, this happens because when you download zxing4p3 library it downloads as "zxing4p3 - v3.4" and this is a bug from the library because even the examples import the library as zxing4p3. What you have to do is to change the library's name to "zxing4p3". I will include it in the wiki, so the people can have it in mind while using the project.

**Comment by agrignard** [comment]
Ok fix (I have updated the wiki accordingly)
