### ISSUE TITLE
ConcurrentModification Exception 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#32]
Press '+' to increase the number of cell in the grid

after few press it sends a ConcurrentModificationException from here:

 public void checkPattern() {
    for (PatternCells pc : PCELLS) {
      pc.checkPattern();
    }
  }

**Comment by JesusGarcia98** [comment]
This exception happened because that method - and the draw method - of Mesh use PCELLS, which means that any change made to it directly affects the other methods. This was fixed by creating a temporal ArrayList and then assigning its value to PCELLS. 

I toyed around increasing and decreasing the blocks for some minutes and the error did not occur.

**Comment by agrignard** [comment]
OK great I test it  doesn't happen anymore
Good job 

Just for the records here is the commit that fixed it 
https://github.com/CityScope/CSL_Lima/commit/5443a66e88065c15f5c50322a630810d2478aa74
